# Generated by Django 4.2.21 on 2025-06-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_ordered',
        ),
    ]
