# Generated by Django 4.2.21 on 2025-06-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_order_items_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
