# Generated by Django 4.2.21 on 2025-05-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_products_color_products_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_detail',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
