# Generated by Django 4.2.21 on 2025-05-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_products_category_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category_detail',
        ),
    ]
