# Generated by Django 4.2.21 on 2025-05-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_products_category_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
