# Generated by Django 4.2.21 on 2025-05-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
