# Generated by Django 4.2.3 on 2025-02-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Customer_id',
            new_name='customer_id',
        ),
    ]
