# Generated by Django 4.2.3 on 2025-02-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_customer_id_profile_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
