# Generated by Django 4.2.3 on 2025-02-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_airlines'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlines',
            name='iata_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
