# Generated by Django 4.2.3 on 2025-03-09 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0006_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Booking Issue', 'Booking Issue'), ('Refund Request', 'Refund Reqiest'), ('Baggage Inquiry', 'Baggage Inquiry'), ('Flight Change', 'Flight Change'), ('Other', 'Other')], default='Other', max_length=50)),
                ('status', models.CharField(choices=[('open', 'open'), ('In progress', 'In progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.airlines')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
