# Generated by Django 4.2.3 on 2025-03-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('support_agent', 'Support Agent'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
