# Generated by Django 4.2.3 on 2025-03-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='response',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
